using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace gob.fnd.Dominio.Digitalizacion.Entidades.CorteDiario.ABSaldos
{
    public class ABSaldosGen
    {
        public int Regional { get; set; }
        public string? NumCte { get; set; }
        public int Sucursal { get; set; }
        public string? ApellPaterno { get; set; }
        public string? ApellMaterno { get; set; }
        public string? Nombre1 { get; set; }
        public string? Nombre2 { get; set; }
        public string? TnFinal { get; set; }
        public string? RazonSocial { get; set; }
        public string? ActividadPrinc { get; set; }
        public string? Sector { get; set; }
        public string? TpoPersona { get; set; }
        public string? EstadoInegi { get; set; }
        public string? MunicipioInegi { get; set; }
        public string? LocalidadInegi { get; set; }
        public string? NumCredito { get; set; }
        public string? NumProducto { get; set; }
        public string? Divisa { get; set; }
        public string? CodLinea { get; set; }
        public decimal PorcRecProp { get; set; }
        public string? TipoCartera { get; set; }
        public DateTime? FechaApertura { get; set; }
        public DateTime? FechaVencim { get; set; }
        public decimal TasaInteres { get; set; }
        public string? TasaFijaOVar { get; set; }
        public string? CodTasaBase { get; set; }
        public decimal Superficie { get; set; }
        public string? Actividad { get; set; }
        public decimal RelGarcred { get; set; }
        public string? CodigoInsCre { get; set; }
        public string? CodInversion { get; set; }
        public string? CodCaract { get; set; }
        public string? CodCaract2 { get; set; }
        public string? CodAgricola { get; set; }
        public string? CodProd { get; set; }
        public string? StatusContable { get; set; }
        public decimal PorcentajeEstim { get; set; }
        public string? ElegiblePf { get; set; }
        public decimal PorcentajeFiFo { get; set; }
        public string? BanderaFiFo { get; set; }
        public decimal MontoOtorgado { get; set; }
        public decimal MtoMinistraCap { get; set; }
        public decimal SldoCapCont { get; set; }
        public decimal SldoIntCont { get; set; }
        public decimal SldoTotCont { get; set; }
        public decimal SldoTotContval { get; set; }
        public string? NumContrato { get; set; }
        public DateTime? FechaSuscripcion { get; set; }
        public DateTime? FechaVencCont { get; set; }
        public decimal MontoAutoCont { get; set; }
        public decimal MontoEjercido { get; set; }
        public string? TipoCreditoCont { get; set; }
        public string? EsUnionCredito { get; set; }
        public string? DatosRegistro { get; set; }
        public string? CodCalifica { get; set; }
        public int Nocreditos { get; set; }
        public int Noclientes { get; set; }
        public string? CodigoIns { get; set; }
        public decimal PorcenRedesc { get; set; }
        public string? FactorAplica { get; set; }
        public string? TipoMargen { get; set; }
        public decimal MargenInter { get; set; }
        public string? LineaDesc { get; set; }
        public decimal TasaFon { get; set; }
        public string? NumControl { get; set; }
        public string? Marcacred { get; set; }
        public int CodSujetoFj { get; set; }
        public string? CalEdosFin { get; set; }
        public decimal CapVig { get; set; }
        public decimal IntFinVig { get; set; }
        public decimal IntFinVigNp { get; set; }
        public decimal CapVen { get; set; }
        public decimal IntFinVen { get; set; }
        public decimal IntFinVenNp { get; set; }
        public decimal IntNorVig { get; set; }
        public decimal IntNorVigNp { get; set; }
        public decimal IntNorVen { get; set; }
        public decimal IntNorVenNp { get; set; }
        public decimal IntDesVen { get; set; }
        public decimal IntPen { get; set; }
        public decimal DCapVig { get; set; }
        public decimal DIntFinVig { get; set; }
        public decimal DIntFinVigNp { get; set; }
        public decimal DIntNorVig { get; set; }
        public decimal DIntNorVigNp { get; set; }
        public string? TipoCredito { get; set; }
        public string? TipoDescuento { get; set; }
        public DateTime? FechaIngusgaap { get; set; }
        public int CuotasCap { get; set; }
        public int CuotasCapVen { get; set; }
        public int CuotasInt { get; set; }
        public int CuotasIntVen { get; set; }
        public int DiasVenusgaap { get; set; }
        public int DiasVennopag { get; set; }
        public string? ClaveAsigusgaap { get; set; }
        public string? Ejecutivo { get; set; }
        public string? Unidad { get; set; }
        public DateTime? FechaMinis { get; set; }
        public string? CobroInt { get; set; }
        public string? CobroCapital { get; set; }
        public string? FolioAserca { get; set; }
        public string? CredDemandado { get; set; }
        public decimal ImpPgsCredmnd { get; set; }
        public string? FactorSobretasa { get; set; }
        public string? TipoCalculo { get; set; }
        public decimal Sobretasa { get; set; }
        public string? Medida { get; set; }
        public string? Numprom { get; set; }
        public string? Nomprom { get; set; }
        public int CuotasMora { get; set; }
        public decimal Capital { get; set; }
        public decimal Interes { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Moratorios { get; set; }
        public decimal Total { get; set; }
        public decimal V2601Pt { get; set; }
        public decimal TipoCambio { get; set; }
        public decimal CapitalVal { get; set; }
        public decimal InteresVal { get; set; }
        public decimal SubtotalVal { get; set; }
        public decimal MoratoriosVal { get; set; }
        public decimal TotalVal { get; set; }
        public decimal V2601PtVal { get; set; }
        public decimal MontoDisponible { get; set; }
        public string? ApoyoFirco { get; set; }
        public DateTime? FechaApyfirco { get; set; }
        public decimal IntCobAnt2601 { get; set; }
        public DateTime? FechaEmision { get; set; }
        public string? NumCreditoFira { get; set; }
        public string? NumControlFira { get; set; }
        public string? Almacenadora { get; set; }

    }
}
